apiVersion: v1
kind: ConfigMap
metadata:
  name: lws-manager-config
  namespace: lws-system
data:
  controller_manager_config.yaml: |
    apiVersion: config.lws.x-k8s.io/v1alpha1
    kind: Configuration
    internalCertManagement:
      enable: false
    leaderElection:
      leaderElect: true
