apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openshift-lws-operator-operand
  namespace: openshift-lws-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-lws-operator-operand
subjects:
  - kind: ServiceAccount
    name: openshift-lws-operator
    namespace: openshift-lws-operator